apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: hello-world
deploy:
  kustomize:
    paths:
    - kubernetes-manifests/base
profiles:
  - name: local
    build:
      artifacts:
        - image: hello-world
          context: .
          jib: {}
      local:
        push: false
      tagPolicy:
        sha256: {}
    deploy:
      kustomize:
        paths:
        - kubernetes-manifests/overlays/dev-local
    activation:
    - kubeContext: docker-desktop
  - name: remote
    build:
      artifacts:
      - image: europe-west2-docker.pkg.dev/ejmadkins-dev-workflow-demos/remote-registry/hello-world
        context: .
        jib: {}
      tagPolicy:
        sha256: {}
      googleCloudBuild:
        projectId: ejmadkins-dev-workflow-demos
    deploy:
      kustomize:
        paths:
        - kubernetes-manifests/overlays/dev-remote
    activation:
    - kubeContext: remote-dev-cluster