apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    env: dev-remote
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/ejmadkins-2020-01-06-dev/remote-registry/dev-workflow:skaffold
        name: hello-world
